### ISSUE TITLE
Methods to ensure tree is only modified between ticks

### ISSUE THREAD

**Issue by GammaGames** [bitbrain/beehave#10]
**Is your feature request related to a problem? Please describe.**
I'm prototyping a game that I plan to modify the behavior tree during runtime. I think it would be helpful to have an `add_behavior(node/scene, parent_node)` that adds the node/scene after the tree has processed for the tick.

The same could happen for removing with a `remove_behavior(node/scene, parent_node)`. 

Thoughts?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GammaGames** [comment]
Actually, that might make a debug view a bit of a pain...

Working on a debug helper scene rn, I'll wait to see if I can implement this later

**Comment by bitbrain** [comment]
@GammaGames Closing this as all nodes in beehave are Godot nodes that you can add children to in code dynamically. Feel free to reply why this is still needed but I believe this can be achieved by simply relying on the `add_child` methods.
