### ISSUE TITLE
ERROR: Custom monitor with id '' doesn't exist

### ISSUE THREAD

**Issue by Werninator** [bitbrain/beehave#123]
Godot version: 4.0-rc1

Following error appears while switching scenes inside the editor:
![image](https://user-images.githubusercontent.com/6310506/218267097-13447327-32dc-48fb-a085-020897e457b8.png)

Probably stems from `beehave_tree.gd` `_exit_tree()`, whereas `_process_time_metric_name` might be an empty string and `BeehaveGlobalMetrics` not having been initialized / added to Autoload yet.

**To Reproduce**

Open up a scene that contains a BeehaveTree and one that does not. Switching Scene Tabs should cause this error

**Expected behavior**

No error should appear

**Screenshots**

See above

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by bitbrain** [comment]
Interestingly, this used to work before just fine. Hopefully, this is not a bug with Godot itself. Thank you for spotting this.
