### ISSUE TITLE
Blackboards count as orphans if created dynamically

### ISSUE THREAD

**Issue by Werninator** [bitbrain/beehave#127]
Godot version: 4.0-rc1

As hinted from #122: It seems like, if a blackboard will be initialized at runtime (when there is no Blackboard assigned), it will count as an orphaned node, as it isn't added to the SceneTree.

I added following to `beehave_tree.gd:_ready()`:

```swift
if not blackboard:
    blackboard = Blackboard.new()
    blackboard.name = "Blackboard that has been created at runtime"

print_orphan_nodes()
```
Output:
```
Output: 52714014507 - Stray Node: Blackboard that has been created at runtime (Type: Node)
```

GDUnit4 didn't show me this being an orphan and in general this might not be an issue per se, but it did make me search for why there suddenly was an orphaned node appearing per Instance using a BeehaveTree.

Current workaround is to add a Blackboard and assign it, otherwise you'll have to ignore it. A solution could be to add new Blackboards to the tree.

**To Reproduce**
1. Add BeehaveTree to the Scene without an assigned Blackboard in it

**Expected behavior**
No orphaned node

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: win11

**Comment by bitbrain** [comment]
One workaround could be to do this:
```
if not blackboard:
    blackboard = Blackboard.new()
    add_child(blackboard)
```
this also would allow us to remove this code here:
https://github.com/bitbrain/beehave/blob/godot-4.x/addons/beehave/nodes/beehave_tree.gd#L69

However, we may need to tweak the configuration warnings/validations as we currently expect every child of the tree to be of type `BeehaveNode`

Also, someone could at runtime re-assign the blackboard, in that case we need to make sure to remove the "inner" blackboard from the tree. In case someone unassigns the `blackboard` property again, we'd need to re-add an internal one to the tree.
