### ISSUE TITLE
Don't include gdUnit4 in releases

### ISSUE THREAD

**Issue by Wichamir** [bitbrain/beehave#139]
**Problem**
We have a separate `test` directory for the unit tests and they are not included in releases, but the `addons/gdUnit4` is, although it is not necessary for the end user (or am I missing something?).

**Solution**
Remove `addons/gdUnit4` from `.gitattributes` file.

**Comment by bitbrain** [comment]
Oops! I actually did that change when working on gdUnit but I accidentally discarded the change. Great catch!

**Comment by bitbrain** [comment]
Fixed!
