### ISSUE TITLE
Blurry editor icons

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/beehave#140]
Godot version: 4.0.rc2

**Describe the bug**

Editor icons seem to be blurry (I use 4K monitor with 200% editor scale). This might be related to the fact that the icons do not have editor scaling enabled in the import settings.

![Capture](https://user-images.githubusercontent.com/822035/219473176-e0ac6e10-77d1-48c4-9344-c0647275312a.PNG)

https://docs.godotengine.org/en/latest/development/editor/creating_icons.html#icon-optimization

Currently, even with that flag enabled icons are still blurry: 
![Capture](https://user-images.githubusercontent.com/822035/219474923-b126c423-1ec1-4e10-b7b7-d2c19dc90a8d.PNG), see https://github.com/godotengine/godot/issues/73491 for details.

**Comment by bitbrain** [comment]
Still happening in Godot 4.0.2

**Comment by Calinou** [comment]
This is fixed in 4.1.beta, but won't be cherry-picked to 4.0.x given the scope of the changes required to fix the issue: https://github.com/godotengine/godot/pull/75472
