### ISSUE TITLE
BeehaveTree icon not displaying in online docs

### ISSUE THREAD

**Issue by GeroVeni** [bitbrain/beehave#143]
`BeehaveTree` icon is not properly displaying in [online docs](https://bitbra.in/beehave/#/learn).

![image](https://user-images.githubusercontent.com/9087101/219614839-0393b8ca-8775-4ab4-a1c0-2cbea55a13c7.png)

**Comment by bitbrain** [comment]
Great catch! I fixed this now and created https://github.com/bitbrain/beehave/issues/144 to properly re-introduce icons in the docs.
