### ISSUE TITLE
Use node icons in docs

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/beehave#144]
The current docs do not display any node icons. Although, I pushed the icons into this path: https://github.com/bitbrain/beehave/tree/godot-4.x/docs/assets/icons we now effectively have duplicated the icons on the repository. In case someone wants to update an icon or add a new one, we'd have to do it in two places.

Re-introduce node icons by potentially considering a way to only have them in the addons folder + delete the icons from the docs/assets/icons folder. In case this is not possible, re-introduce them in the docs as usual.

**Comment by FonkinS** [comment]
Btw, do we want the node icons in the Navigation Bar in the Online Doc? Not entirely sure if this is currently possible, as it is in a .MD file. We could either just use emojis, or switch the navbar to be a .HTML file [https://docsify.js.org/#/custom-navbar]

**Comment by thiagola92** [comment]
I don't know docsify but if all we need to do is edit `_sidebar.md`, we could use HTML in markdown files like this:  

```markdown
* [🐝 Getting started](/)
* [📗 Manual](/manual/)
    * [<img src="/beehave/assets/icons/blackboard.svg"> Blackboard](/manual/blackboard.md)
    * [<img src="/beehave/assets/icons/category_leaf.svg"> Leaf Nodes](/manual/leaf_nodes.md)
        * [<img src="/beehave/assets/icons/action.svg"> Action Leaf](/manual/action_leaf.md)
        * [<img src="/beehave/assets/icons/condition.svg"> Condition Leaf](/manual/condition_leaf.md)
    * [<img src="/beehave/assets/icons/category_composite.svg"> Composites](/manual/composites.md)
        * [<img src="/beehave/assets/icons/selector.svg"> Selector](/manual/selector.md)
        * [<img src="/beehave/assets/icons/sequence.svg"> Sequence](/manual/sequence.md)
    * [<img src="/beehave/assets/icons/category_decorator.svg"> Decorators](/manual/decorators.md)
    * [Debugging](/manual/debugging.md)
    * [Performance](/manual/performance.md)
* [🍻 Contribute](/contribute.md)
```

Wouldn't be visible through github  
![image](https://github.com/bitbrain/beehave/assets/9352894/a7f6f3ca-40b8-48b2-a37e-ff333ebd45db)

But would work for the website  
![image](https://github.com/bitbrain/beehave/assets/9352894/e787eafd-8b5c-419d-a0b9-7d604ed4e388)
