### ISSUE TITLE
Tree using InverterDecorator crashes Godot Editor when trying to view in Debug view

### ISSUE THREAD

**Issue by Werninator** [bitbrain/beehave#145]
Godot version: 4.0-rc2

Trying to view a tree containing the InverterDecorator has capped me from viewing any tree in the debug view, even after deleting the Decorator from the tree.

**To Reproduce**
1. Create or modify existing BeehaveTree with InverterDecorator
2. Try to view BeehaveTree in Debug view -> Crash on Click
3. Delete InverterDecorator from BeehaveTree -> still crashes on click

**Expected behavior**
No crash, see BeehaveTree with Decorators in it

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: win11

**Additional context**

Happened on da0ba03

**Comment by bitbrain** [comment]
@Werninator is this still happening on the latest `godot-4.x`?

**Comment by Werninator** [comment]
I thought a new Godot RC was available for a second lol

![image](https://user-images.githubusercontent.com/6310506/220079680-38f67eae-e34a-44e8-95ba-bda22c6bab16.png)

It works! 😄 Closing this ticket
