### ISSUE TITLE
Could not resolve "BeehaveEditorDebugger" because of a parser error

### ISSUE THREAD

**Issue by pbrechtmann** [bitbrain/beehave#148]
Godot version: 4.0 rc2

**Describe the bug**
The BeehaveEditorDebugger is causing errors in the build, preventing behaviour nodes from working.

**To Reproduce**
1. Export the project with default settings
2. Run projectname.console.exe

**Expected behavior**
Behaviors running in the build.

**Screenshots**
![Screenshot_20230219_090251](https://user-images.githubusercontent.com/44525951/219939081-7bf8eb30-804f-43ae-a9d3-b03464272126.png)

**Desktop (please complete the following information):**
 - Windows 11 Desktop

**Minimal Reproduction Project:**
[BeehaveBugTest.zip](https://github.com/bitbrain/beehave/files/10776497/BeehaveBugTest.zip)

**Comment by Werninator** [comment]
I can confirm this behavior. It doesn't result in a crash, it just prevents all BeehaveTrees from running
