### ISSUE TITLE
Too many trees spam error logs

### ISSUE THREAD

**Issue by Werninator** [bitbrain/beehave#170]
My game will have hundreds of BeehaveTrees running at the same time. A little stress test resulted in this:
![image](https://user-images.githubusercontent.com/6310506/222897339-40e90af2-5768-400a-ad46-60ee28e25e65.png)
(lol typo in error)

**Describe the solution you'd like**
Title explains it - option to exclude certain trees from the performance metrics / debugging.

**Describe alternatives you've considered**
Alternatively we could have a lightweight BeehaveTree that strictly does AI stuff - allowing you to swap the .gd-Files / Nodes depending on what you need.

Maybe a global option to deactivate all perf/debug for Production Builds would be great, might be another issue though.

**Comment by bitbrain** [comment]
@Werninator what if you increase the limit in the Godot settings?

**Comment by Werninator** [comment]
@bitbrain raising the max_queued_messages (which is by default 2048) to 100k even causes those messages to happen

**Comment by bitbrain** [comment]
The issue I see is that we should not "probe" every tree all the time but only probe it when it is actively selected in the debug view. @DarkMessiah 

For the performance monitoring, we might want to exclude them by default but have an option to start probing them if required.

**Comment by Werninator** [comment]
@bitbrain @DarkMessiah Here is a minimal project that replicates those messages
[message_queue_overflow.zip](https://github.com/bitbrain/beehave/files/10891906/message_queue_overflow.zip)
