### ISSUE TITLE
Sequence not running all children nodes while a child is in the RUNNING state

### ISSUE THREAD

**Issue by jeanphillips31** [bitbrain/beehave#176]
Godot version: 4.0.0 Stable

**Describe the bug**
While a Sequence's child is in the RUNNING status, it will not process any other children every tick until the RUNNING process returns either SUCCESS or FAILURE

**To Reproduce**
1. Create a Sequence Node
2. Create at least 2 children nodes
3. Set one node to be in the RUNNING state every tick
4. Print something in the second node and it will not print anything until after the first time

**Expected behavior**
The Sequence should still process other children nodes while a child is in the RUNNING state.

**Screenshots**
![image](https://user-images.githubusercontent.com/27161820/226871778-bfb2683e-6d7b-4086-aa2b-e728370bcde8.png)
"PLAYER WAS NOT FOUND" should be printed every tick instead of just once.

**Desktop (please complete the following information):**
 - OS: Windows 10, in engine, not a built application

**Comment by bitbrain** [comment]
This behavior is expected, as described [here](https://behaviortree.github.io/BehaviorTree.CPP/SequenceNode/):

> "Tick again" means that the next time the sequence is ticked, the same child is ticked again. Previous sibling, which returned SUCCESS already, are not ticked again.

When a sequence node encounters a running child node, it will pause execution of the sequence and wait for the running child node to complete before continuing with the next child node. So, after the running child node returns a running status, the sequence node will not immediately proceed to the next child node. Instead, it will re-tick the running child node on the next update and wait for it to complete.

What you are looking for instead is the parallel node https://github.com/bitbrain/beehave/issues/58 that will execute all its children (even if some of them are currently running). That node will return `SUCCESS` when all children returned `SUCCESS` eventually. However, that node is not implemented yet. Feel free to raise a pull request.

Alternatively, use the `ReactiveSequence` node if you want to have all nodes prior to the currently running node to be executed each frame.
