### ISSUE TITLE
Improve documentation of nodes

### ISSUE THREAD

**Issue by BenjaTK** [bitbrain/beehave#180]
**Is your feature request related to a problem? Please describe.**
The documentation is frustratingly confusing. I may be the only one, but I some things are explained very poorly. Let's take the selector node explanation for example: "Selector nodes will attempt to execute each of its children and reports SUCCESS status code in case one of the children reports a SUCCESS status code. In case all children report a FAILURE status code, this node will also return FAILURE status code. This node will attempt to process all its children every single tick, even if one of them is currently RUNNING already." I feel like this is way too convoluted. For a beginner in behavior trees like me, it was very hard to understand and I had to look up external sources.

**Describe the solution you'd like**
In the selector node example, we can say "The selector nodes will attempt to execute each of its children in order until one of them reports SUCCESS, in which case the selector will report SUCCESS aswell and it will stop. In case all children report FAILURE, this node will also return FAILURE. [...]"

**Comment by bitbrain** [comment]
Anyone feel free to raise a pull request!
