### ISSUE TITLE
Many strange errors while trying to setup my project

### ISSUE THREAD

**Issue by tavurth** [bitbrain/beehave#182]
Godot version: x.x.x

**Describe the bug**
I'm trying to setup a decision tree as follows:

<img width="629" alt="Screenshot 2023-04-19 at 19 52 46" src="https://user-images.githubusercontent.com/100964/233080561-9a4f045e-b77b-41ae-89c7-bfd2340bb4a2.png">

However I'm running into many many many errors like this:

<img width="695" alt="Screenshot 2023-04-19 at 19 52 59" src="https://user-images.githubusercontent.com/100964/233080623-9faf7e24-d372-4dce-a574-8db71ac41655.png">

**To Reproduce**
I'm not sure yet, I will update with more information as and when I figure it out

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Latest

**Comment by tavurth** [comment]
Adding the following debbugging:

<img width="580" alt="Screenshot 2023-04-19 at 19 54 30" src="https://user-images.githubusercontent.com/100964/233081020-d75f0492-3813-4fb1-9788-91f41d1ef66e.png">

Results in:

<img width="669" alt="Screenshot 2023-04-19 at 19 54 45" src="https://user-images.githubusercontent.com/100964/233081100-4973982b-27bb-48a9-85d5-ef89127101a9.png">

**Comment by tavurth** [comment]
Finally it was because:

`GoToOwnRoom.tscn`

```gdscript
var target: NodePath


func _init(new_target: NodePath):
	print(new_target)
	self.target = new_target


func tick(actor: Node, blackboard: Blackboard) -> int:
	print("IN GOTO OWN ROOM")
	var target_node = blackboard.get_node(self.target)

```

Target was undefined 🤔 

I guess I misunderstood something from the docs

**Comment by bitbrain** [comment]
These errors are quite misleading, to be honest. We probably should improve the way we log these things - @DarkMessiah @lostptr @Werninator thoughts?

**Comment by tavurth** [comment]
@bitbrain thank you for making this btw. I've been learning most of the day and aside from these small hiccups I can see the power behind this idea. Fits very well with Godot nodes also.

**Comment by tavurth** [comment]
Also this could well be related to this issue in Godot 4.x:

https://github.com/godotengine/godot/issues/73358

I very often have annoying and hard to track down bugs at the moment because 4.x doesn't really want to report where they are coming from, sometimes not even reporting at all!

**Comment by tavurth** [comment]
![photo_2023-04-19 22 47 10](https://user-images.githubusercontent.com/100964/233140758-6daacd10-8d88-4dac-b7dd-b4d76f31f64b.jpeg)

:)
