### ISSUE TITLE
Add a new node type `DataLeaf`

### ISSUE THREAD

**Issue by tavurth** [bitbrain/beehave#184]
**Is your feature request related to a problem? Please describe.**

I have the following:
<img width="332" alt="Screenshot 2023-04-20 at 18 47 11" src="https://user-images.githubusercontent.com/100964/233356810-3d0ac479-efb8-4801-a94c-35fc551c4004.png">

However I would much prefer:
```gdscript
BeeHaveTree
└── GoToOwnRoomAction
    └── SequenceStarComposite
        ├── HasOwnership
        │   └── DataLeaf (OwnBedroom)
        └── GoTo
            └── DataLeaf (OwnBedroom)
```

**Describe the solution you'd like**
I want the character to `GoTo` some place, but I don't want to have to specify that place in code every time.
I want to describe a list of places:

```gdscript
OwnBedroom
OwnLivingRoom
OwnBathroom
```

And then apply these as a child of the `GoTo` action to modify it's behaviour.

**Describe alternatives you've considered**
I will just write these nodes myself.

**Comment by tavurth** [comment]
`DataLeaf.gd`
```gdscript
extends Node2D

@export var name: String = "NO_NAME"
@export var value: Variant = null


func _init(new_name: String, new_value: Variant) -> void:
	self.name = new_name
	self.value = new_value

	var path = str(get_script().get_path())

	if len(name) < 1:
		push_warning("%s has no name")

	if value == null:
		push_warning("%s has no value")
````

**Comment by tavurth** [comment]
`DataLeaf.gd`
```gdscript
@tool
@icon("res://addons/beehave/icons/action.svg")
class_name DataLeaf
extends Node2D

func get_value(_actor, _blackboard: Blackboard) -> Variant:
	var path = str(get_script().get_path())
	push_warning("%s has no getter, please override this" % path)

	return null
```

`OwnRoom.gd`
```gdscript
class_name OwnBedroom
extends DataLeaf

func get_value(actor, _blackboard: Blackboard) -> Variant:
	return Ownership.find_first_of_type(actor, "bedroom")
```

**Comment by tavurth** [comment]
Which has allowed me to simplify my logic as follows:

<img width="323" alt="Screenshot 2023-04-20 at 19 14 05" src="https://user-images.githubusercontent.com/100964/233362633-16b3e81e-84da-42ad-b4e3-f99b45e15632.png">

`has_own.gd`
```gdscript
extends ConditionLeaf

@onready var target_node: DataLeaf = get_child(0)


func tick(actor: Node, blackboard: Blackboard) -> int:
	var has_ownership = target_node.get_value(actor, blackboard)

	if has_ownership:
		return SUCCESS

	return FAILURE
```

`own_bedroom.gd`
```gdscript
class_name OwnBedroom
extends DataLeaf


func get_value(actor, _blackboard: Blackboard) -> Variant:
	return Ownership.find_first_of_type(actor, "bedroom")
```

`go_to.gd`
```gdscript
class_name GoTo
extends ActionLeaf

@onready var target_node: DataLeaf = get_child(0)


func tick(actor: Node, blackboard: Blackboard) -> int:
	var move_target = target_node.get_value(actor, blackboard)

	if move_target == null:
		return FAILURE

	if not actor.has_target():
		actor.move_to(move_target.get_global_position())

	if not actor.navigation.is_navigation_finished():
		return RUNNING

	return SUCCESS


func interrupt(actor: Node, _blackboard: Blackboard) -> void:
	actor.stop()
```

**Comment by bitbrain** [comment]
This is exactly what blackboards are for: https://bitbra.in/beehave/#/manual/blackboard

The idea is that you can store information _per node_ in the blackboard, like this:
```gdscript
extends ConditionLeaf

@export var identifier = ""

func tick(actor: Node, blackboard: Blackboard) -> int:
	var has_ownership = blackboard.get_value("ownership", false, identifier)

	if has_ownership:
		return SUCCESS

	return FAILURE
```
Then inside the tree (within the action + condition leaf) you can give it a custom identifier (e.g. "Captain") so the blackboard values you are setting/getting are local to that identifier. You can alternatively, also use `get_instance_id()` in case you want to track values unique to that very instance. The advantage of a blackboard is that you can keep your entire tree _stateless_.

Obviously, you need to set the value also somewhere: this can be done inside the ActionLeaf for example.

**Comment by tavurth** [comment]
@bitbrain yes I found that way through `Blackboard`, however I will continue to use this `DataLeaf` idea as I find it more visual and easier to debug.

When I first watched your woodcutter video on youtube as an introduction to this plugin, my thought was:
"Oh that's a shame you have to inject values in that way"

And so I'm guessing newcomers to Godot will also find that a sticking point.

**Comment by tavurth** [comment]
I've gone a bit further now and defined these types:

`DataActionLeaf.gd`
```gdscript
class_name DataActionLeaf
extends ActionLeaf

@onready var target_node: DataLeaf


func _get_configuration_warning() -> PackedStringArray:
	if get_child_count() > 0:
		if get_child(0) is DataLeaf:
			return PackedStringArray()

	return PackedStringArray(["A child of type DataLeaf is required"])


func _enter_tree() -> void:
	if get_child_count() < 1:
		var path = str(get_script().get_path())
		push_error("%s: A child of type DataLeaf is required" % path)
		return

	self.target_node = get_child(0)
```

`DataConditionLeaf.gd`
```gdscript
class_name DataConditionLeaf
extends ConditionLeaf

@onready var target_node: DataLeaf


func _get_configuration_warning() -> PackedStringArray:
	if get_child_count() > 0:
		if get_child(0) is DataLeaf:
			return PackedStringArray()

	return PackedStringArray(["A child of type DataLeaf is required"])


func _enter_tree() -> void:
	if get_child_count() < 1:
		var path = str(get_script().get_path())
		push_error("%s: A child of type DataLeaf is required" % path)
		return

	self.target_node = get_child(0)
```

Which mean I can simplify my scripts:

`go_to.gd`
```gdscript
@tool
class_name GoTo
extends DataActionLeaf


func tick(actor: Node, blackboard: Blackboard) -> int:
	var move_target = target_node.get_value(actor, blackboard)

	if move_target == null:
		return FAILURE

	if not actor.has_target():
		actor.move_to(move_target.get_owned_position())

	if not actor.navigation.is_navigation_finished():
		return RUNNING

	return SUCCESS


func interrupt(actor: Node, _blackboard: Blackboard) -> void:
	actor.stop()
```


`has_own.gd`
```gdscript
@tool
class_name HasOwn
extends DataConditionLeaf


func tick(actor: Node, blackboard: Blackboard) -> int:
	var has_ownership = target_node.get_value(actor, blackboard)

	if has_ownership:
		return SUCCESS

	return FAILURE
```

**Comment by tavurth** [comment]
I prefer this way in general because when I'm working with AI I can very easily modify the location or item that the subtree is referring to.

<img width="285" alt="Screenshot 2023-04-20 at 20 04 08" src="https://user-images.githubusercontent.com/100964/233374706-90931e0b-cd8d-49ea-a693-06254a1a81ba.png">

<img width="615" alt="Screenshot 2023-04-20 at 20 04 17" src="https://user-images.githubusercontent.com/100964/233374754-17b45c68-7613-42d9-bce4-905cf92b8ac3.png">


I don't need to code anything, just write out the name of what it is they should look for

**Comment by tavurth** [comment]
<img width="322" alt="Screenshot 2023-04-20 at 20 06 00" src="https://user-images.githubusercontent.com/100964/233375228-1bd40432-825c-4271-963a-99486d449752.png">

It also becomes very easy visually to determine where the AI is going, without requiring a new complex type for each action.

I'm sure I will abstract this further, but this seems to me like a good first step.

**Comment by tavurth** [comment]
An interesting idea here is that we could also separate `Owned` and `Bedroom`, into a `CombinationDataLeaf` and a `DataLeaf`

Which could create a tree possibility like:

```gdscript
Find
└── Owned
    └── Bedroom
```

```gdscript
Find -> ConditionalLeaf
Own -> CombinerDataLeaf -> get_child(0).get_value().find_owned()
Bedroom -> find_all_bedrooms()
```

Or even
```gdscript
Find
└── Enemy
    └── Bedroom
```

Although this seems to be unneeded for my game, and so I will not implement now.

**Comment by tavurth** [comment]
> The advantage of a blackboard is that you can keep your entire tree _stateless_.

As far as I've so far seen, `DataLeaf` also keeps the tree stateless, is there something I'm missing here?

Aha perhaps because you are injecting actors?

As far as I understood `Blackboard` is a global state for the entire tree?


```gdscript
class_name OwnBedroom
extends DataLeaf

func get_value(actor, _blackboard: Blackboard) -> Variant:
	return blackboard.get_value("bedroom")
```

**Comment by tavurth** [comment]
Another example use case for the `DataLeaf`, stateless:

<img width="329" alt="Screenshot 2023-04-23 at 12 26 23" src="https://user-images.githubusercontent.com/100964/233821415-bfab5db9-15c1-43c2-9aa2-405fb05dfb6f.png">


`AvailableWorkstation.gd`
```gdscript
class_name AvailableWorkstation
extends DataLeaf


func sort_by_distance(a: Node, b: Node, actor: CharacterBody2D) -> bool:
	return (\
		actor.position.distance_squared_to(a.position)\
		<\
		actor.position.distance_squared_to(b.position)\
	)


func is_available(workstation: Node, actor: CharacterBody2D) -> bool:
	return workstation.is_available(actor)


func get_value(actor: CharacterBody2D, _blackboard: Blackboard) -> Variant:
	var workstations = get_tree()\
		.get_nodes_in_group("workstation")\
		.filter(is_available.bind(actor))
	
	workstations\
		.sort_custom(sort_by_distance.bind(actor))

	if not len(workstations):
		return null

	return workstations[0]
```

`SetUsed.gd`
```gdscript
@tool
class_name SetUsed
extends DataActionLeaf


func tick(actor: Node, blackboard: Blackboard) -> int:
	var target = target_node.get_value(actor, blackboard)
	if not target:
		return FAILURE

	target.set_used_by(actor)
	return SUCCESS
```

Would be nice to see the `DataLeaf` on the flow chart, perhaps I will implement that in future.
![telegram-cloud-photo-size-2-5339080473248385081-y](https://user-images.githubusercontent.com/100964/233821499-9e753564-034f-4cac-8acf-7832b17c7488.jpg)

**Comment by bitbrain** [comment]
The purpose of a leaf in the context of behavior trees is either a condition or an action (as any node needs to handle the tick correctly). I'd argue that while a `DataLeaf` works, it is an anti-pattern in the context of behavior trees:

- any state that is local to one particular node should be part of that node
- any state that is shared between multiple nodes should be stored in the blackboard
- any node in the behavior tree needs to indicate its status through the `SUCCESS`, `RUNNING` or `FAILURE` status
- Conditions & Actions are not allowed to have children. This is because they are leafs and the idea is that a leaf is in fact the lowest element in a tree

Feel free to use this concept within your game itself, though. It is a valid concept to utilize (e.g. implement your own action node with child nodes that have state). However, for Beehave I a not convinced this is the right thing to introduce. Feel free to [open a discussion](https://github.com/bitbrain/beehave/discussions) though to see if more people have that same challenge. In that case we might want to rework the data management concept of this addon alltogether.
