### ISSUE TITLE
Default function for setting values

### ISSUE THREAD

**Issue by TrayserCassa** [bitbrain/beehave#196]
First of all, amazing videos and nice Tutorials. Thank you for help me to create a game <3

**Is your feature request related to a problem? Please describe.**
I followed the youtube tutorial and found out that you overwrite the _ready function from the root node. I was confused because the extended class wasn't the BeehaveTree it was BeehaveRoot. I ignored that and try it. It took me a while to find out that I've overwritten the ready method, so blame on me. 

**Describe the solution you'd like**
After this I had a Idea: I use the BeehaveTree and export stuff that is needed for the AI and on a function which exists in the BeehaveTree I can overwrite it in the my own script. 

**Describe alternatives you've considered**
I could use a node, which acts like a Proxy, but for me it feels better if I can use the BeehaveTree directly where I will decide what the NPC does. 

**Additional context**
Maybe the images makes more sense. 

In my own script which extends from BeehaveTree:
![image](https://github.com/bitbrain/beehave/assets/12298964/012c1d69-23bd-469c-9027-ad42a1195657)

In the BeehaveTree script:
![image](https://github.com/bitbrain/beehave/assets/12298964/416fe641-0568-4694-8952-90ffbe044a94)

Main scene where I put stuff together:
![image](https://github.com/bitbrain/beehave/assets/12298964/ea6f1bb7-598a-4162-826a-93717c79888e)

**Comment by bitbrain** [comment]
Why can't you override the `_ready()` function instead? Something like:
```
func _ready() -> void:
   super._ready()

   # your code here
```
should do the trick.

**Comment by TrayserCassa** [comment]
I'm so stupid.. sorry 
I'm coding now for to long in go :sweat_smile:
