### ISSUE TITLE
Unit tests with gdUnit (Godot 4.0 only)

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/beehave#2]
Currently, there is no way of telling if a change will break this addon or not. Introduce unit tests to ensure that any new PR will not break existing logic.

This should only apply to the `godot-4.x` branch since maintaining two separate versions of GUT is difficult to maintain and once Godot 4 launches, the `godot-3.x` branch goes into maintenance mode.

GUT is one option but after much consideration, gdUnit4 has a better and cleaner integration:

https://github.com/MikeSchulze/gdUnit4

## Tests to write

- [x] simple composites
- [x] advanced composites (star nodes)
- [x] advanced composites (random nodes)
- [x] decorators
- [x] complex behavior tree setup (end-2-end)
- [x] simple blackboard
- [x] advanced blackboard (shared between multiple trees)
- [x] interrupt logic for running nodes
- [x] beehave tree methods (currently running action + get last condition)

**Comment by Nemesis-AS** [comment]
Which unit testing framework would you recommend?
Currently I'm aware of GUT - https://github.com/bitwes/Gut
and WAT - https://github.com/AlexDarigan/WAT
There may be other ones as well

**Comment by bitbrain** [comment]
I ported GUT to Godot 4 so we should use that one!

https://github.com/bitwes/Gut/tree/godot_4

**Comment by creadicted** [comment]
> I ported GUT to Godot 4 so we should use that one!
> 
> https://github.com/bitwes/Gut/tree/4.0

Do you mean https://github.com/bitwes/Gut/tree/godot_4 ?

**Comment by bitbrain** [comment]
@creadicted good catch! It got renamed.

**Comment by bitbrain** [comment]
I discovered https://github.com/MikeSchulze/gdUnit4 and that one looks much more promising. I will raise a PR soon to add these tests!

**Comment by bitbrain** [comment]
Added a first set of unit tests here: https://github.com/bitbrain/beehave/pull/105
