### ISSUE TITLE
AssetLib preview image has broken URL

### ISSUE THREAD

**Issue by timothyqiu** [bitbrain/beehave#21]
Godot version: 3.5

**Describe the bug**

AssetLib preview image uses `https://github.com/bitbrain/beehave/raw/main/example.jpg` as preview image.

The branch name needs to be updated.

**To Reproduce**

Go to <https://godotengine.org/asset-library/asset/1349>, or open the addon's detail dialog in Godot Editor.

**Screenshots**

![ksnip_20220820-094540](https://user-images.githubusercontent.com/372476/185724588-5225b1ba-3706-4d69-9302-8a9c9ecaeda9.png)
![ksnip_20220820-094526](https://user-images.githubusercontent.com/372476/185724590-9aed2fb4-bc23-4629-923a-bcf1a8b98910.png)

**Comment by bitbrain** [comment]
Great catch and thank you for raising this. I submitted a fix to the asset library to resolve this.

**Comment by bitbrain** [comment]
![Capture](https://user-images.githubusercontent.com/822035/185754779-6d02e6ab-6645-4fe8-a01e-0de416bdab67.JPG)

Problem solved!
