### ISSUE TITLE
Add tooltips for behave tree exposed properties

### ISSUE THREAD

**Issue by Nrosa01** [bitbrain/beehave#215]
**Is your feature request related to a problem? Please describe.**
Actor Node Path, Blackboard and Custom Monitor properties don't have tooltip. Of course I can go to the docs and read there but it should have tooltips too for faster workflow

![image](https://github.com/bitbrain/beehave/assets/62796415/21c3e2d6-2b88-456b-84c6-1aa3b5459df0)

**Describe the solution you'd like**
Add tooltips to those properties

**Describe alternatives you've considered**
I don't think there are alternative solutions for this

**Additional context**
None

**Comment by Nrosa01** [comment]
I think it would also be nice to have descriptions in nodes to complement this. Example:
![image](https://github.com/bitbrain/beehave/assets/62796415/56bb9899-47cd-472e-a278-56ba7d5ab43b)

**Comment by lostptr** [comment]
> I think it would also be nice to have descriptions in nodes to complement this.

Interesting...there are already some descriptions for the classes used in the nodes. In theory, I think Godot should "inherit" the class description if there is no custom description for the node. What do you think?

**Comment by Nrosa01** [comment]
> > I think it would also be nice to have descriptions in nodes to complement this.
> 
> Interesting...there are already some descriptions for the classes used in the nodes. In theory, I think Godot should "inherit" the class description if there is no custom description for the node. What do you think?

It should do that, if I recall correctly some addon somehow had default editor descriptions, but after searching for it now I'm not even sure if it's possible or whether I dreamt it.

I'm a little busy now but I'll check this again at night and update you all in this conversation. Having this would make things easier for new users like me

**Comment by bitbrain** [comment]
![Screenshot 2023-11-17 221439](https://github.com/bitbrain/beehave/assets/822035/275e9d6f-2ce7-4ed2-a8b0-096911926dbd)

looks like this issue is fixed now in the latest Godot `4.1.2.stable`
