### ISSUE TITLE
Add process mode to BehaveTree component

### ISSUE THREAD

**Issue by Nrosa01** [bitbrain/beehave#217]
**Is your feature request related to a problem? Please describe.**
I would like to be able to choose if my tree will run on physics process or normal process.

**Describe the solution you'd like**
In behave_tree.gd, expose a new enum variable that let's user choose between IDLE and PHYSICS. Encapsulate _physics_process code in an execute() function and use in process or physics process accordingly. Example

## Current implementation

```gdscript
func _physics_process(delta: float) -> void:
	if Engine.is_editor_hint():
		return

	# Start timing for metric
	var start_time = Time.get_ticks_usec()

	blackboard.set_value("can_send_message", _can_send_message)

	if _can_send_message:
		BeehaveDebuggerMessages.process_begin(get_instance_id())

	if self.get_child_count() == 1:
		tick()

	if _can_send_message:
		BeehaveDebuggerMessages.process_end(get_instance_id())

	# Check the cost for this frame and save it for metric report
	_process_time_metric_value = Time.get_ticks_usec() - start_time
```

## Desired implementation

```gdscript
# Below the first enum
enum PROCESS_MODE
{
	IDLE,
	PHYSICS
}

# Above or Below enabled var
@export var tree_process_mode: PROCESS_MODE = PROCESS_MODE.PHYSICS

func execute(delta: float) -> void:
	if Engine.is_editor_hint():
		return

	# Start timing for metric
	var start_time = Time.get_ticks_usec()

	blackboard.set_value("can_send_message", _can_send_message)

	if _can_send_message:
		BeehaveDebuggerMessages.process_begin(get_instance_id())

	if self.get_child_count() == 1:
		tick() # We could pass delta here (see my other issue)

	if _can_send_message:
		BeehaveDebuggerMessages.process_end(get_instance_id())

	# Check the cost for this frame and save it for metric report
	_process_time_metric_value = Time.get_ticks_usec() - start_time

func _physics_process(delta: float) -> void:
	if tree_process_mode == PROCESS_MODE.PHYSICS:
		execute(delta)

func _process(delta: float) -> void:
	if tree_process_mode == PROCESS_MODE.IDLE:
		execute(delta)
```

**Describe alternatives you've considered**
None

**Additional context**
I'll make a PR on this tomorrow if I have time with the other issues too

**Comment by Nrosa01** [comment]
I'll write this here. 

As this PR might conflict with #216 PR. I'll wait until we can close that one (either by mergin it or by deciding to not do so) before doing this one. This PR not having delta in the tick function while the other having it might cause problems depending on git giving conflict or the merge order that might cause the delta parameter to be lost in `behave_tree.gd`

At least I think this PR is easier than the other one (just one file to modify) and shuldn't affect any other thing.

**Comment by bitbrain** [comment]
As elaborated on https://github.com/bitbrain/beehave/discussions/243, #216 will not be part of Beehave 2.x, so this ticket is safe to implement.

**Comment by bitbrain** [comment]
@Nrosa01 let me know if you are happy with this! https://github.com/bitbrain/beehave/pull/251
