### ISSUE TITLE
Debugger crashes Godot 4.2-dev5

### ISSUE THREAD

**Issue by RafaelVidaurre** [bitbrain/beehave#219]
Godot version: 4.2-dev5

**Describe the bug**
Opening the debugger graph edit view crashes the engine (not a standard error, a crash).

As far as I could tell, the engine crashes when a node is added as a child of the GraphEdit node.

**To Reproduce**
1. Run the game with at least one active behavior tree
2. Go to the debugger and click on the Beehive tab
3. Click on any behavior tree from the list

**Expected behavior**
The graph showing the behavior tree should appear.

**Screenshots**

https://github.com/bitbrain/beehave/assets/1808674/8bbc3aa5-3c2d-450d-b5c3-44fc44baefd7

**Desktop (please complete the following information):**
 - OS: MacOS, Sonoma

**Additional context**
Updating the function names of `get_zoom_hbox()` does not solve this, although this change is also required due to GraphEdit's latest breaking changes.

P.S. Even though there's an incomplete PR #214  attempting to solve this issue, I thought it'd be better to have this as a proper bug report

**Comment by bitbrain** [comment]
This will be resolved by https://github.com/bitbrain/beehave/pull/214
