### ISSUE TITLE
interrupt doesn't get called

### ISSUE THREAD

**Issue by HoutarouOreki** [bitbrain/beehave#220]
Godot version: 4.1.1
Beehave version: 2.7.5 and [cf18be7](https://github.com/bitbrain/beehave/commit/cf18be7b18d8d11f83b6dc67280d6432ba5a6abb)

**Describe the bug**
I have an ActionLeaf. 

I expect its method `interrupt` to be called when the Leaf stops being ticked while still running.

My expectations are not met.

**Scenario where it works wrong**

- GoToFetchable (1) is running
- IsFetching (2) turns to false, so GoToFetchable stops being ticked, due to (2) and (1) being under a reactive sequence
- SittingAction (3) is now being ticked

![image](https://github.com/bitbrain/beehave/assets/16261733/bff19d3d-a0f1-4974-a8e5-e1cd467eed26)

GoToFetchable (1) never gets the `interrupt` or `after_run` methods called during this scenario, both on master and 2.7.5.
By reading the manual, I thought `interrupt` would get called. I want to handle this interruption but the method doesn't get called.

To add to this, on failure/success of GoToFetchable (1):
- 2.7.5: both `after_run` and `interrupt` get called, which is wrong
- latest commit: `after_run` gets called, which is as expected

**Desktop:**
Linux Ubuntu 20.04

**Comment by lostptr** [comment]
Hey, I could work on this but it would be better if we had a minimal reproduction project

**Comment by HoutarouOreki** [comment]
https://github.com/HoutarouOreki/BeehaveInterruptRepro

**Comment by HoutarouOreki** [comment]
Works now, thank you 💙
