### ISSUE TITLE
Update 3.x to have the same features as 4.x whenever is possible

### ISSUE THREAD

**Issue by lostptr** [bitbrain/beehave#223]
**Is your feature request related to a problem? Please describe.**
People are trying to use the 3.x branch but there are several things missing. One example is that there is no `interrupt()` method and this makes `SequenceStar` (3.x) and `Sequence` (4.x) have very different behaviors.

**Describe the solution you'd like**
Port all the features from the 4.x branch to 3.x, specially the ones involving how composites work so that beehave trees work the same in both branches.

**Comment by bitbrain** [comment]
3.x is not meant to have feature parity with 4.x but only bugs should be addressed. However, if anyone feels strongly about a certain feature they want in 3.x they can raise a PR to add it
