### ISSUE TITLE
Repeater Decorator

### ISSUE THREAD

**Issue by lostptr** [bitbrain/beehave#230]
### **Is your feature request related to a problem? Please describe.**
I would like to suggest a decorator to repeat their child X times as I have many enemies that would use this behavior and I dont think is too specific to my project.

### **Describe the solution you'd like**
A decorator that runs its child for the specified number of times or when the child returns `FAILURE`. A child execution is only counted when it returns `SUCCESS` (if returns `FAILURE` it stops immediatly, returning `FAILURE` as well).

Also, this could be the icon: (keep in mind that the Limiter's icon is this ![image](https://github.com/bitbrain/beehave/assets/21160216/efa0e673-b0d4-41f3-a6cd-c4858da95f66))
![image](https://github.com/bitbrain/beehave/assets/21160216/f201a6ac-b40d-468d-b57e-87a609a5760a)

### **Describe alternatives you've considered**
I cannot use a Limiter to this purpose for two reasons. 
It doesnt work as I expect with long running tasks and it always returns FAILURE, forcing me to always use it with a Succeeder.

To quote the docs:
> The `Limiter` node executes its child a specified number of times (x). When the maximum number of ticks is reached, it returns a `FAILURE` status code. 

This is good to use in conditions that return imediately but it doesnt work well with long running tasks. It could be a bug but right now if a Limiter is set to execute 3 times it will do this:
```
Limiter::before_run()
child.tick() -> RUNNING, returning RUNNING as well
child.tick() -> RUNNING, returning RUNNING as well
child.tick() -> RUNNING, returning RUNNING as well
done executing child, returning FAILURE
Limiter::after_run()
```

**Comment by RedstoneParadox** [comment]
> This is good to use in conditions that return imediately but it doesnt work well with long running tasks. It could be a bug but right now if a Limiter is set to execute 3 times it will do this:

Based on what the docs say, it definitely is intentional. I think for long-running actions, it helps to think of ticking not as ticking the action itself but requesting an update on the status. For example, a long-running action might involve navigating to a point using a `NavigationAgent2D/3D`; while the action node might be the one to start that, the actual movement is probably going to be handled directly in the actor class, so at that point, the action node just checks whether navigation was successful.

To be honest, I think it might just be better to add an exported boolean to `Limiter` that controls whether it should count an execution if the child returns running.

**Comment by lostptr** [comment]
> Based on what the docs say, it definitely is intentional.

Yeah, I thought so.

Still, for something so simple as "do this 3 times" I would have to set a boolean and add a inverter/succeder since `Limiter` returns `FAILURE` when it reaches the 3 times. 

Thats why I am suggesting a new decorator since it is another "concept". Limiter is for something that you want to retry a couple of times until it works or a limit has been reached. Kinda like retrying to make an HTTP request if it fails the first time.

A repeater would be for something that you want to do that exact amount of times (unless something goes wrong). I know is possible to do this with exported properties because both decorators are basically the same. 

However, Sequence and Selector are also almost the same, but having them being two separate nodes helps with usability (they can have different icons, for example)
