### ISSUE TITLE
Documentation for the behaviour of composite nodes is misleading

### ISSUE THREAD

**Issue by rxlecky** [bitbrain/beehave#248]
The current documentation for the behaviour of composite nodes contains conflicting information and inaccuracies.

Firstly, both Sequence and Selector documentation pages state the following:

> Every tick, the Selector/Sequence node processes all its children, even if one of them is currently RUNNING.

This is wrong, since only the Reactive variants process all child nodes, regardless of the return status.

Secondly, the **Types of Sequence/Selector Nodes** tables in the Sequence and Selector documentation pages correctly illustrate the tick behaviour of each composite node sub-type, depending on the child node's return status. However, it uses the term _restart_ to mean that the composite starts ticking from the first child, as opposed to _tick again_ which means that it ticks from where it left off the last time. This is confusing, because the term 'restart' is explained in [Composites](https://bitbra.in/beehave/#/manual/composites?id=restarting-a-composite) page as follows:

> **Restarting a composite**
>
> If a parent node restarts a child node, it means that the parent node will start the child node from scratch the next time it is ticked. This means that any progress made by the child node will be reset, and it will start its execution from the beginning.

This suggests it's the child node that gets restarted - i.e. it receives the `before_run` callback - and not the execution of the sequencer node itself gets restarted. This is contrary to how the term is used in the tables on Sequence and Selector pages. It is also contrary to the heading, i.e. *Restarting a composite** suggests it's the composite itself that gets restarted, not the child node.

Relevant documentation pages:
https://bitbra.in/beehave/#/manual/composites
https://bitbra.in/beehave/#/manual/selector
https://bitbra.in/beehave/#/manual/sequence

**Comment by bitbrain** [comment]
Thank you for the detailed report.

> This is wrong, since only the Reactive variants process all child nodes, regardless of the return status.

This is untrue: as you can see [in this example](https://github.com/bitbrain/beehave/blob/godot-4.x/addons/beehave/nodes/composites/sequence.gd#L23) **RUNNING** children will always be executed. The difference to a reactive composite is that a reactive composite will [always restart from the beginning](https://github.com/bitbrain/beehave/blob/godot-4.x/addons/beehave/nodes/composites/sequence_reactive.gd#L40), while the normal version re-ticks a running node.

> [...] This suggests it's the child node that gets restarted

I agree on this, the documentation can be improved here.

**Comment by bitbrain** [comment]
@rxlecky please feel free to give me your feedback on https://github.com/bitbrain/beehave/pull/249 which hopefully addresses this issue.

**Comment by rxlecky** [comment]
Oh, that was quick! Thanks for taking a look, I believe improving the docs will help the new users.

> > This is wrong, since only the Reactive variants process all child nodes, regardless of the return status.
>
> This is untrue: as you can see [in this example](https://github.com/bitbrain/beehave/blob/godot-4.x/addons/beehave/nodes/composites/sequence.gd#L23) RUNNING children will always be executed. The difference to a reactive composite is that a reactive composite will [always restart from the beginning](https://github.com/bitbrain/beehave/blob/godot-4.x/addons/beehave/nodes/composites/sequence_reactive.gd#L40), while the normal version re-ticks a running node.

Oh, I'm sorry, that was poor wording on my end. I meant exactly what you said, you just worded it better. 🙂

Anyway, in my opinion, my point is still valid. The documentation says that every tick the composite processes all its children. Maybe I'm misunderstanding what the term _processing the children_ is used for, but in my opinion, this makes it sound like the composite is restarted and all child nodes are ticked on every tick - which is the behaviour of only the reactive composites and that's what I meant with my original comment. Well, at least that's how I understood this section of the documentation the first time I read it and what I found confusing. And even now, I'm not sure what its actual intended meaning is, to be honest.

**Comment by bitbrain** [comment]
Tick Again = only the latest running node will be ticked again
Restart = even with a currently running action, all nodes until that running action will be reticked.

**Comment by rxlecky** [comment]
Sorry if I'm not making myself clear. I fully understand the terms `Tick Again` and `Restart` in the context of the composite nodes and I understand how the different types of composite nodes behave, depending on the return status of their children.

All I'm saying is that this section of the documentation:

> Every tick, the Selector/Sequence node processes all its children, even if one of them is currently RUNNING.

to me sounds like selector and sequence nodes are restarted every tick, because it says that all child nodes are processed, i.e. ticked, on every frame.

**Comment by rxlecky** [comment]
My suggestion would be to reword this paragraph to something like this:

> Every tick, the Selector/Sequence node either restarts and starts ticking its children from the beginning, or it continues where it left off last frame and starts ticking from the child that was ticked last on the last frame. The exact behaviour depends on the type of Selector/Sequence node and on the return status of the child node that was ticked last on the last frame.

And then this is followed by the section which has a neat table, exactly explaining the behaviours depending on the type.

**Comment by bitbrain** [comment]
Restart means that during a single frame (the moment the next tick happens), all children will be ticked until the running child is reached (within a single frame). So the sequence node loops through the children and ticks them within a single tick.

**Comment by rxlecky** [comment]
Hahah, this seems like it's either me misunderstanding what you're saying or the other way around 😀 

So, again. The documentation says that on every frame, the sequence node ticks ALL of its children. However, this is not quite true for the normal sequence node. On first frame, the sequence node starts ticking all its children in order, starting from the first one, until either all of them return `SUCCESS` or one of them returns `RUNNING`. If one of them returned `RUNNING`, on the next frame, the sequence will only tick the running child node. Not all of them, just the running one - and possibly the child nodes following it, if the running child has completed and returned `SUCCESS`.

**Comment by rxlecky** [comment]
`
