### ISSUE TITLE
Debug panel broken

### ISSUE THREAD

**Issue by sml0240** [bitbrain/beehave#266]
Godot version: 4.2-stable_arch_linux

**Describe the bug**
The debug beehave panel is showing double the trees that is active, everytime i restart the game the amount is doubled.
I also cannot expand the trees, it is just showing the list of trees.

**To Reproduce**
1. Start game.
2. Go to debug window, Beehave panel.
3. Look at the list of trees. try to open one.
4. Restart game.
5.  Go to debug window, Beehave panel, and look at amount of trees.

**Expected behavior**
Being able to click on a tree to show a debug view of the tree.
The amount of trees not being doubled everytime i start the game.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: EndavourOS
 - 
** Additional Info **
Error in output:
res://addons/beehave/debug/debugger_tab.gd:66 - Invalid set index 'visible' (on base: 'Nil') with value of type 'bool'.

**Comment by bitbrain** [comment]
Thank you for raising this.

**Comment by sml0240** [comment]
You can close this issue since it was a mistake by me, i had not updated to latest version even though i thought i did.
Thank you for this addon, its great!
