### ISSUE TITLE
Tick rate inbetween 0 and 1

### ISSUE THREAD

**Issue by Shadowblitz16** [bitbrain/beehave#272]
**Is your feature request related to a problem? Please describe.**
Allow us to execute our behaviors with a tick rate of less then 1 second

**Describe the solution you'd like**
Allow this to be something like 0.001 as a minimum
![image](https://github.com/bitbrain/beehave/assets/2453707/1994beff-b74a-40ef-9f1b-2b6baebfc5ed)

**Describe alternatives you've considered**
Nothing yet

**Additional context**
I am trying to recreate the structure found here... https://www.youtube.com/watch?v=YHUQY2Kea9U
![image](https://github.com/bitbrain/beehave/assets/2453707/9164415a-9527-415b-9892-70b9051ca71e)

**Comment by bitbrain** [comment]
Tick rate is measured in frames. 1 means every frame, 2 means every 2 frames. Having a value smaller than 1 therefore does not make sense.

What is the exact problem you are trying to solve here?

**Comment by Shadowblitz16** [comment]
interesting my logic must have a bug in it then.
my player was only changing directions every second or so.
