### ISSUE TITLE
drawing?

### ISSUE THREAD

**Issue by Shadowblitz16** [bitbrain/beehave#274]
**Is your feature request related to a problem? Please describe.**
I would like to draw stuff like in Node2D._draw

**Describe the solution you'd like**
a draw method with a canvas item and a blackboard passed

**Describe alternatives you've considered**
I have considered make a bunch of nodes

**Additional context**
I am trying to draw a 2d aiming reticle

**Comment by bitbrain** [comment]
@Shadowblitz16 you can already do that. All nodes have a draw method you can use to draw custom shapes.

In Godot, it is usually not advised to have both drawing logic and game logic in the same node. Instead, Godot promotes composition over inheritance, where you have dedicated nodes (such as Sprite2D). Therefore, adding drawing capabilities to Beehave other than the already default draw methods is out of scope.

In case you REALLY need it though, store the blackboard in a variable inside tick() and then access it in your draw method.
