### ISSUE TITLE
change @export var actor_node_path to @export var actor: Node

### ISSUE THREAD

**Issue by hantaogo** [bitbrain/beehave#277]
In my game, I embed a behavior tree into each state of the state machine, and the behavior tree is dynamically loaded. However, the behavior tree requires specifying the attribute "actor_node_path." My state code is in a separate script, making it unable to specify this path. After reviewing the source code, it seems that modifying it this way might be possible.

```GDScript
# beehave_tree.gd
@export var actor : Node:
	set(anp):
		actor = anp
		if Engine.is_editor_hint():
			update_configuration_warnings()

func _ready() -> void:
	......
	if not actor:
		actor = get_parent()

# my code:
@export var behaviour: PackedScene = null

func enter_state():
	bt = behaviour.instantiate() as BeehaveTree
	bt.actor = ai.actor
	bt.blackboard = ai.board
	add_child(bt)
```

**Comment by bitbrain** [comment]
Thanks for raising this @hantaogo! The reason this has never been changed is to not break older projects using Beehave. To circumvent this, you could try setting this property: https://github.com/bitbrain/beehave/blob/godot-4.x/addons/beehave/nodes/beehave_tree.gd#L101

Alternatively, we could support both setting actor and node path directly (and it would then set actor_node_path respectively)

**Comment by hantaogo** [comment]
thank you.
