### ISSUE TITLE
Improve documentation on using blackboards

### ISSUE THREAD

**Issue by mrjshzk** [bitbrain/beehave#279]
As per community request, improve the documentation on blackboards, especially on various use cases.

> Hello and sorry to bother! I've been really enjoying using your plugin! But I've haven't really found a way to use blackboards.
Could you explain it to me or add more documentation?
> 
> Thank you in advance,
> Miguel Silva

**Comment by mrjshzk** [comment]
Also, sorry to bother again. I'm trying to make this simple AI but I have a problem.
If MoveToRandomPoint is RUNNING, it does not check if it is SeeingPlayer. How do you think I could do this?
![image](https://github.com/bitbrain/beehave/assets/115943663/03af837a-e1e9-4770-8d2c-9a69a352cf55)

Thanks in advance,
Miguel Silva

**Comment by bitbrain** [comment]
@mrjshzk for any issues or questions regarding the behaviour of beehave, feel free to [open a new discussion](https://github.com/bitbrain/beehave/discussions) or [ask the community on our Discord](https://discord.com/invite/CKBuE5djXe).

**Comment by bitbrain** [comment]
Closed by https://github.com/bitbrain/beehave/pull/283
