### ISSUE TITLE
Can't create beehave tree

### ISSUE THREAD

**Issue by Shadowblitz16** [bitbrain/beehave#282]
Godot version: v4.2.1.stable.official [b09f793f5]

**Describe the bug**
I get errors when trying to create a new beehave tree.
No node is created

**To Reproduce**
1. Download Beehave
2. Enable it
3. Get Errors I already reported here https://github.com/bitbrain/beehave/issues/270
4. Try to create new BeehaveTree and scene root
5. Get this error ...
```
  Cannot get class ''.
  editor/editor_data.cpp:581 - Parameter "p_object" is null.
  editor/scene_tree_dock.cpp:2452 - Parameter "child" is null.
```
6. Clear logs
7. Create Node as scene root.
8. Add BeehaveTree as child.
9. Get this error ...
```
  Cannot get class ''.
  editor/editor_data.cpp:581 - Parameter "p_object" is null.
  editor/scene_tree_dock.cpp:2452 - Parameter "child" is null.
```

**Expected behavior**
It should work without errors

**Screenshots**
https://github.com/bitbrain/beehave/issues/270

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04, Linux kernal 6.2.0-39-generic (64 bit)
 - Browser: Firefox 121.0 (64-bit)
 - Version : Idk?

**Additional context**
I really want to use this plugin

**Comment by bitbrain** [comment]
Which beehave version are you using? Can you ensure to use the latest v2.7.9 please? As any prior version is incompatible with Godot 4.2 (as it has breaking changes)

https://github.com/bitbrain/beehave/releases/tag/v2.7.9
