### ISSUE TITLE
Is this plugin available in c#?

### ISSUE THREAD

**Issue by NetCodersX** [bitbrain/beehave#297]
**Is your feature request related to a problem? Please describe.**
Is this plugin available in c#?

**Describe the solution you'd like**
Can c# use the current plug-in?

**Comment by lostptr** [comment]
Not...yet!
Checkout #285 it explains that in the next major version it will support basically any language.

Right now, only gdscript sadly

**Comment by NetCodersX** [comment]
@lostptr 
That's great.
When is the next version expected to be released?

**Comment by bitbrain** [comment]
> When is the next version expected to be released?

When it's ready. :)

The idea would be though that an unstable 3.0-dev version will be released fairly early in the next couple weeks hopefully.
