### ISSUE TITLE
The export var enabled is useless isn't it？

### ISSUE THREAD

**Issue by kaluluosi** [bitbrain/beehave#30]
Godot version: x.x.x

**Describe the bug**
![image](https://user-images.githubusercontent.com/1620585/187610887-f6e8f328-8f21-4262-b68e-b285f50d0d16.png)

wether you set enabled true or false，the code doesn't use enabled to enable/disable behavior tree root. Tree still running.

**Expected behavior**
export var enable can disable behavior tree process on ready or dynamic disable process in runtime.

**Comment by Nemesis-AS** [comment]
The `beehave_root.gd` does have `enable()` and `disable()` methods for enabling/disabling them during runtime. So this variable should not be modified at runtime.
The `_ready` function could be modified to enable/disable based on this variable

**Comment by kaluluosi** [comment]
> The `beehave_root.gd` does have `enable()` and `disable()` methods for enabling/disabling them during runtime. So this variable should not be modified at runtime. The `_ready` function could be modified to enable/disable based on this variable

may be we can add setter function to set_enable.

**Comment by bitbrain** [comment]
Closing this, as this issue is solved in Godot 4.
