### ISSUE TITLE
Beehave doesn't output print statements (help needed)

### ISSUE THREAD

**Issue by ca3gamedev** [bitbrain/beehave#303]
I will leave this issue here, because mainly I want it indexed by google, so It can help others new users.

My issue is that there's not proper documentation on how to get signals working so far.
The tutorial seems to miss the setup stages, so I was unable to understand how to set up the tree so the leafs can do their job.

So far what I understand is that I need a root node, and then a sequencer node or a selector node.
Then I need to create a new node and a new script with a derived class from the leafs nodes.

But my issue is that I don't get any output if I do just the tick function.
Any help or explanation on how to set up the trees and leaves would be greatly appreciated.

EDIT : Added a screenshot of my tree.
![tree](https://github.com/bitbrain/beehave/assets/115381195/c5dc5a69-1095-40a6-bfe1-f14415e069c5)

**Comment by tristan-f-r** [comment]
What's the source code of `IDLE CHECK` and `IDLE Action`?

**Comment by ca3gamedev** [comment]
_IDLE CHECK_
```
extends ConditionLeaf

func tick (action, blackboard):
	
	return RUNNING
```

`IDLE ACTION`
```

extends ActionLeaf

func tick(actor, blackboard):
	
	print("IDLE TEST")
	
	return SUCCESS

```

**Comment by tristan-f-r** [comment]
> _IDLE CHECK_
> 
> ```
> extends ConditionLeaf
> 
> func tick (action, blackboard):
> 	
> 	return RUNNING
> ```
> 
> `IDLE ACTION`
> 
> ```
> 
> extends ActionLeaf
> 
> func tick(actor, blackboard):
> 	
> 	print("IDLE TEST")
> 	
> 	return SUCCESS
> ```

The reason why `IDLE TEST` isn't printing is that your previous node is `RUNNING`. If your sequence is atomic, it would work as expected.

**Comment by ca3gamedev** [comment]
Ah, seems I got it.

SUCESS and FAILURE are condition checks, are done once.

RUNNING is a loop condition, and should be used to keep the leaf running.

Thanks!!!!!

**Comment by ca3gamedev** [comment]
Added final advice to people lurking here.

You need a selector node, which will be the parent of a sequence node.
The selector will pick the sequences based on their failure return check.
