### ISSUE TITLE
After editing script to extend a Beehave node the scene tree does not update the icon

### ISSUE THREAD

**Issue by ryan-linehan** [bitbrain/beehave#305]
Godot version: Godot Mono v4.2.1

**Describe the bug**
After editing script to extend a Beehave node the scene tree does not update the icon

**To Reproduce**
1. Create new scene 
2. Attach script to the node
3. extend any of the beehave classes
4. The scene tree does not update

**Expected behavior**
When editing a script to extend a Beehave node the scene tree's icon reflects after saving. It is not until you reload the scene that the icon takes.

**Screenshots**
![image](https://github.com/bitbrain/beehave/assets/12516772/2aa244b5-3b77-4a66-8575-dfce7b248d44)

**Comment by bitbrain** [comment]
I suspect this must be a Godot bug - nothing to do with Beehave itself. Can you reproduce this with non-beehave nodes, too? @RcubDev

**Comment by ryan-linehan** [comment]
I think you're right this does occur inside the editor with normal nodes. I think it presents itself as worse because of the workflow for the plugin. I add an ActionLeaf to the scene tree and it automatically adds its internal script to the node (unlike godot's default nodes). So I have to detach the script and re-add the script to add my own implementation of the ActionLeaf. I think if that workflow is fixed this is not as much of an issue. 

"The only way to add a scriptless custom class is via C++ module or GDExtension." This is an old reddit thread so maybe something is different now:

https://www.reddit.com/r/godot/comments/zo0hyj/make_custom_nodetypes_less_scriptlike/

But it sounds like with the beehave 3.0 coming the workflow issue would be fixed
