### ISSUE TITLE
Preset some action/condition scene 

### ISSUE THREAD

**Issue by kaluluosi** [bitbrain/beehave#32]
**Is your feature request related to a problem? Please describe.**

Some common nodes are suitable for making as scenes and built-in , and users can quickly use them by instantiating scenes.

For example, wait action, check blackboard key condition, set blackboard key action, and clear blackboard key action, log action.

![image](https://user-images.githubusercontent.com/1620585/187653750-3e45eac1-cefa-44c3-9e2b-605842f4eb23.png)

**Describe the solution you'd like**
Preset some scene in plugin.  Users use them by instantiating scenes.

**Comment by creadicted** [comment]
To be honest, I like it that the plugin does not provide too many sample nodes. I would rather add such nodes to a documentation then in to the library, but that's just me...

**Comment by bitbrain** [comment]
Closing this one I am afraid. This addon is supposed to be more of a library and less of a framework. I would love to have the concept of a "behaviour library" where people can share their behaviours with others. Unfortunately, I do not know a good way to do that yet. I may reopen this once more people have the demand for some sort of "behaviour library"
