### ISSUE TITLE
Could not find base class "_BASE_" error log

### ISSUE THREAD

**Issue by FabriceCastel** [bitbrain/beehave#334]
Godot version: 4.2.1

**Describe the bug**
When starting up the editor, the following LSP error gets printed out to console:
```
  Failed parse script res://script_templates/BeehaveNode/default.gd
  Could not find base class "_BASE_".
```

**To Reproduce**
1. Install Beehave
2. See error logs when opening the project

**Expected behavior**
No error logs

**Additional context**
This is a symptom of a Godot engine issue -> https://github.com/godotengine/godot/issues/79236

I'm not expecting a fix to the Godot engine here, but I would appreciate some kind of a workaround to not see those annoying logs every time I open my project :/ AFAIK it's non-breaking, just.. very very annoying (at least for anyone who likes to keep their console output tidy).

**Comment by LeandroLibanio28H** [comment]
There should be a .gdignore file inside script_templates folder so the editor won't load these files. Are you sure you have installed the addon correctly?

**Comment by LeandroLibanio28H** [comment]
If there's no .gdignore file, you could just put the file there, the errors and warnings will be gone this way.

**Comment by FabriceCastel** [comment]
Ah, during the install I copied the files over using the GUI, which doesn't display dotfiles so the `.gdignore` didn't get copied over. Adding it back in seems to resolve the issue :+1:
