### ISSUE TITLE
Docs have wrong type name in sidebar

### ISSUE THREAD

**Issue by ghost** [bitbrain/beehave#335]
**Describe the bug**
In the sidebar of the docs, there are 2 selector tabs, when the second one should be "Simple Parallel"

**To Reproduce**
1. Go to docs
2. Look in sidebar

**Expected behavior**
It should say "Simple Parallel"

**Comment by scrahe** [comment]
<img width="1354" alt="Screen Shot 2024-05-04 at 8 44 34 PM" src="https://github.com/bitbrain/beehave/assets/55860416/f6425f6f-3c22-46e8-86af-a31cdc72cbde">
