### ISSUE TITLE
It's good and time for make the tutorial demo builtin

### ISSUE THREAD

**Issue by kaluluosi** [bitbrain/beehave#34]
**Is your feature request related to a problem? Please describe.**
Since #31 we only export addon, we can contain demo project folder , example project folder in the root folder. 
It's good for test and learn behave.

**Describe the solution you'd like**
We can builtin this tutorial demo inside.
[![tutorial-thumbnail](https://img.youtube.com/vi/n0gVEA1dyPQ/0.jpg)](https://www.youtube.com/watch?v=n0gVEA1dyPQ)

It won't export and install to user's project.
It provide a good demo for they to test and use this plugin.
And we can maintain both in the same project and for test.

**Example:**
I make myself a demo in local for test and learn.
![image](https://user-images.githubusercontent.com/1620585/188768680-66b7b7bc-f674-4554-beaa-4497a8333ec1.png)
![GIF](https://user-images.githubusercontent.com/1620585/188768644-8153c221-7266-432e-aa72-48edfd59ce65.gif)
When I modify behave source code, I just run this demo as **smoke test**.

**Comment by bitbrain** [comment]
@kaluluosi this is actually a great idea! I might do it via a git sub-module + command, though. If I apply changes in the future to https://github.com/bitbrain/godot-tutorials (e.g. upgrading to Godot 4) I want it to be in one place.

Thoughts?

**Comment by kaluluosi** [comment]
> @kaluluosi this is actually a great idea! I might do it via a git sub-module + command, though. If I apply changes in the future to https://github.com/bitbrain/godot-tutorials (e.g. upgrading to Godot 4) I want it to be in one place.
> 
> Thoughts?

That's great! You known I like your tutorials demo(goblin farm), it's an awesome playground for learn and test behavior tree.
Wait in hope. 👍

**Comment by kaluluosi** [comment]
@bitbrain 
I'm new in godot and gamedev. I want to ask or discuss some game development issues with you for help. How can I contact you? By mail?

**Comment by bitbrain** [comment]
@kaluluosi I am mostly quite busy but we have already quite a large community (600+ members) that are probably very happy to help! [Feel free to join our Discord](https://discord.com/invite/CKBuE5djXe) and ask in the #programming channel for advice!
