### ISSUE TITLE
Add documentation comments

### ISSUE THREAD

**Issue by Wichamir** [bitbrain/beehave#51]
**Is your feature request related to a problem? Please describe.**
It would be nice to have documentation for the most important classes like BeehaveRoot, ActionLeaf etc. Especially for people, who are yet learning behavior trees.

**Describe the solution you'd like**
Godot 4 adds [documentation comments](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_documentation_comments.html), so adding docs would be very easy.

For example:
![image](https://user-images.githubusercontent.com/53086728/198894995-3016bca6-9aae-4501-b09c-cb2136f3f08d.png)

Results in:
![image](https://user-images.githubusercontent.com/53086728/198895014-d8ee89b1-bf40-4b7c-ba79-48077c67aac5.png)
![image](https://user-images.githubusercontent.com/53086728/198895053-6df6bb95-7445-4e00-806c-0380593b4a64.png)

**Comment by bitbrain** [comment]
I love this!

**Comment by lostptr** [comment]
Can I work on this? Seems easy enough to just dump the descriptions in the readme into the classes.

**Comment by bitbrain** [comment]
@lostptr no need to ask! Just pick up whatever you want to work on. Any contribution is highly appreciated.
