### ISSUE TITLE
Switch to static typing

### ISSUE THREAD

**Issue by Wichamir** [bitbrain/beehave#57]
**Is your feature request related to a problem? Please describe.**
Some parts of the this plugin's code use static typing, others don't. Just for the sake of consistency and readability it would be nice to use it everywhere. Static typing reduces bugs and enables completion hints. In Godot 4.x it also boosts performance.

**Describe the solution you'd like**
Add type hints everywhere (or at least wherever it's possible). Of course the programmers using Beehave will still be able to use dynamic typing in their projects, if they wish so. It's just that the codebase of the plugin itself will be entirely statically typed.

**Comment by bitbrain** [comment]
For the person picking this up: one thing to keep in mind is that within Godot 3 there are cyclic dependencies when trying to use static typing everywhere. With Godot 4 this will be fixed, though.

**Comment by lostptr** [comment]
Should there be two pull requests then? One for the godot 3 branch with limited typing and one with full typing for godot 4 branch? Sorry if thats basic knowledge, I've only ever used git working alone.

**Comment by bitbrain** [comment]
@lostptr yeah, sounds good!
