### ISSUE TITLE
Include with plugin a script template for BeehaveNode

### ISSUE THREAD

**Issue by Wichamir** [bitbrain/beehave#78]
**Is your feature request related to a problem? Please describe.**
Designing behavior trees requires making a ton of separate scripts, where every one of them has to have an overridden tick method. Defining it for every new script quickly becomes tedious.

**Describe the solution you'd like**
Just include a script template for BeehaveNode (and derived classes) with a predefined overridden tick method.
Create a template script inside `res://script_templates/BeehaveNode/` (that's where Godot searches for project-scope script templates by default) and make a .gdignore file inside `res://script_templates/` so the scripts are ignored when parsed.
[Here's docs about it.](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html)

**Comment by bitbrain** [comment]
Templates are a great idea! We probably should offer two templates:

- Beehave Action Template
- Beehave Condition Template

**Comment by Wichamir** [comment]
> We probably should offer two templates

What would be the difference between them?

For my project I started using something as simple as this:
![image](https://user-images.githubusercontent.com/53086728/208268488-c32c1770-8608-4bad-8f95-fe44c1e9bf3b.png)

Then when I create a script...
![image](https://user-images.githubusercontent.com/53086728/208268531-380cbb3e-6a63-4127-9d03-6012d79eb9d5.png)
I get this:
![image](https://user-images.githubusercontent.com/53086728/208268574-7aa86ab6-97a3-44a2-b5e1-a2f8d1bef19f.png)

Simple, but still saves quite a bit of time. Maybe we should add a comment in the function's body explaining what code should be inserted into tick, similarly to built-in default Node template?

**Comment by bitbrain** [comment]
Ah, I was not aware of placeholders! Yes, wonderful idea. Feel free to raise a PR.
