### ISSUE TITLE
Track performance metrics inside Godot

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/beehave#89]
Godot recently introduced performance monitoring: https://docs.godotengine.org/en/latest/tutorials/scripting/debug/custom_performance_monitors.html

The idea is that we can track various metrics in Godot and it will be displayed inside the performance tab. Possible metrics we can track:

| Metric Name | Description | Implemented |
|---|---|---|
| `beehave/tree_id/process_time` | The total process time per frame tick for the whole behaviour tree | https://github.com/bitbrain/beehave/pull/103 |
| `beehave/node_count` | The number of total beehave nodes in the scene | not yet |
| `beehave/active_count` | Number of active behaviour trees in the scene | not yet |

**Comment by bitbrain** [comment]
Feel free to suggest any other metrics that we could start tracking.

**Comment by goudcode** [comment]
Performance per tree is almost finished. I will open a PR for this in the next comming days.
